# Generated by Django 3.0.5 on 2020-04-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('visited', models.BooleanField()),
                ('what_to_eat', models.TextField(max_length=250)),
            ],
        ),
    ]
