# Generated by Django 3.0.5 on 2020-04-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200408_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiverCruise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('river', models.CharField(choices=[('D', 'Danube'), ('E', 'Elbe'), ('V', 'Vltava'), ('R', 'Rhone')], default='D', max_length=1)),
            ],
        ),
    ]
