# Generated by Django 3.0.5 on 2020-04-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rivercruise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rivercruise',
            name='river',
            field=models.CharField(choices=[('D', 'Danube'), ('E', 'Elbe'), ('R', 'Rhone')], default='D', max_length=1),
        ),
    ]
